name: test it

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: test it

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
        # supported Node.js release schedule: https://nodejs.org/en/about/releases/
        browser:
          - {version: 113, launch: Chrome}
          - {version: 124, launch: Chrome}
          - {version: 125, launch: Chrome}
          - {version: 126.0.6439.0, launch: Chrome}
          - {version: 126.0.6440.0, launch: Chrome}
          - {version: 126, launch: Chrome}
          - {version: stable, launch: Chrome}
          - {version: latest-esr, launch: Firefox}
          - {version: latest, launch: Firefox}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          package.json
          app/package.json

    - name: remove default installed chrome
      if: ${{ matrix.browser.launch == 'Chrome' }}
      run: sudo apt remove google-chrome-stable

    - name: Use ${{ matrix.browser.launch }} ${{ matrix.browser.version }}
      if: ${{ matrix.browser.launch == 'Chrome' }}
      uses: browser-actions/setup-chrome@v1
      id: setup-chrome
      with:
        chrome-version: ${{ matrix.browser.version }}

    - run: chrome --version
      if: ${{ matrix.browser.launch == 'Chrome' }}

    - name: Use ${{ matrix.browser.launch }} ${{ matrix.browser.version }}
      if: ${{ matrix.browser.launch == 'Firefox' }}
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: ${{ matrix.browser.version }}

    - run: firefox --version
      if: ${{ matrix.browser.launch == 'Firefox' }}

    - run: npm i -g .

    - run: npm i

    - run: npm run test-ci-smoke -- launch=${{ matrix.browser.launch }}
    - run: npm run test-ci-dev -- launch=${{ matrix.browser.launch }}
